apply android style guide
Exception: GastroLocation.java, otherwise the JSON import breaks.

Source: http://source.android.com/source/code-style.html#follow-field-naming-conventions